import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate} from 'react-router-dom';
import {BarChart3,Users,Kanban,Mail,BrainCircuit,Plus,Search,TrendingUp} from 'lucide-react';
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import './styles.css';

const initialLeads=[
{id:1,name:'Sarah Chen',company:'Nova Labs',email:'sarah@novalabs.ai',status:'Qualified',source:'LinkedIn',value:18000,score:92},
{id:2,name:'Michael Reed',company:'Orbit Systems',email:'michael@orbit.io',status:'Proposal',source:'Website',value:24000,score:84},
{id:3,name:'Aisha Khan',company:'Vertex Digital',email:'aisha@vertex.dev',status:'Contacted',source:'Apollo',value:12000,score:76},
{id:4,name:'Daniel Smith',company:'Acme Cloud',email:'daniel@acme.cloud',status:'New',source:'Referral',value:9000,score:61}
];
const data=[{name:'Mon',leads:18},{name:'Tue',leads:24},{name:'Wed',leads:21},{name:'Thu',leads:32},{name:'Fri',leads:28},{name:'Sat',leads:15}];
function App(){const [leads,setLeads]=useState(initialLeads);const [q,setQ]=useState('');const [active,setActive]=useState('Dashboard');const nav=[['Dashboard',BarChart3],['Leads',Users],['Pipeline',Kanban],['AI Assistant',BrainCircuit],['Campaigns',Mail]];const filtered=leads.filter(l=>(l.name+l.company+l.email).toLowerCase().includes(q.toLowerCase()));
function addLead(){const id=Date.now();setLeads([...leads,{id,name:'New Prospect',company:'New Company',email:'prospect@example.com',status:'New',source:'Manual',value:10000,score:65}]);}
return <div className="app"><aside><div className="brand"><div className="logo">AI</div><div><b>LeadFlow</b><small>AI CRM SaaS</small></div></div><nav>{nav.map(([n,I])=><button className={active===n?'active':''} onClick={()=>setActive(n)} key={n}><I size={18}/>{n}</button>)}</nav><div className="user"><div className="avatar">RG</div><div><b>Ritesh Gaur</b><small>Admin</small></div></div></aside><main><header><div><span className="eyebrow">OVERVIEW</span><h1>{active}</h1></div><div className="actions"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search leads..."/></div><button className="primary" onClick={addLead}><Plus size={17}/> Add Lead</button></div></header>{active==='Dashboard'?<><section className="cards"><Card title="Total Leads" value={leads.length+1248} delta="+12.5%" icon={<Users/>}/><Card title="Qualified" value={leads.filter(x=>x.score>75).length+326} delta="+8.2%" icon={<TrendingUp/>}/><Card title="Pipeline Value" value="$186.4K" delta="+18.4%" icon={<Kanban/>}/><Card title="Conversion" value="24.8%" delta="+4.1%" icon={<BarChart3/>}/></section><section className="grid"><div className="panel chart"><div className="panelhead"><div><h2>Lead Acquisition</h2><p>Qualified leads generated this week</p></div><span className="pill">Last 7 days</span></div><ResponsiveContainer width="100%" height={260}><BarChart data={data}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="leads" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div><div className="panel ai"><div className="ai-icon"><BrainCircuit/></div><h2>AI Insights</h2><p>Your highest-value opportunity is <b>Orbit Systems</b>. Their engagement increased 34% this week.</p><button className="secondary">View AI recommendations →</button></div></section><section className="panel"><div className="panelhead"><div><h2>Recent Leads</h2><p>AI-prioritized prospects that need attention</p></div><button className="link" onClick={()=>setActive('Leads')}>View all →</button></div><LeadTable leads={filtered.slice(0,4)}/></section></>:active==='Leads'?<section className="panel"><div className="panelhead"><div><h2>Lead Management</h2><p>Manage and qualify your prospects</p></div><button className="primary" onClick={addLead}><Plus size={17}/> Add Lead</button></div><LeadTable leads={filtered}/></section>:active==='Pipeline'?<Pipeline leads={leads}/>:<section className="empty panel"><BrainCircuit size={42}/><h2>{active}</h2><p>This module is ready for the next integration.</p></section>}</main></div>}
function Card({title,value,delta,icon}){return <div className="stat"><div className="staticon">{icon}</div><span>{title}</span><strong>{value}</strong><em>{delta} this month</em></div>}
function LeadTable({leads}){return <div className="table"><div className="tr th"><span>Lead</span><span>Company</span><span>Status</span><span>AI Score</span><span>Value</span></div>{leads.map(l=><div className="tr" key={l.id}><span><b>{l.name}</b><small>{l.email}</small></span><span>{l.company}<small>{l.source}</small></span><span><i className={'status '+l.status.toLowerCase()}>{l.status}</i></span><span><b>{l.score}</b>/100</span><span><b>${l.value.toLocaleString()}</b></span></div>)}</div>}
function Pipeline({leads}){const cols=['New','Contacted','Qualified','Proposal'];return <section className="pipeline">{cols.map(c=><div className="column" key={c}><h3>{c}<span>{leads.filter(x=>x.status===c).length}</span></h3>{leads.filter(x=>x.status===c).map(l=><div className="deal" key={l.id}><b>{l.company}</b><small>{l.name}</small><strong>${l.value.toLocaleString()}</strong><div className="score">AI {l.score}</div></div>)}</div>)}</section>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
